# Generated by Django 4.2.5 on 2024-10-29 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('analise', 'Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=100)),
                ('experiencia', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50)),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('analise', 'Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=100)),
                ('experiencia', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50)),
                ('formacao', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
