# Generated by Django 4.2.5 on 2024-10-27 02:01

import django.core.files.storage
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Dispobivel', 'disponivel'), ('Adotado', 'adotado')], default='Desconhecido', max_length=10)),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], default='Desconhecido', max_length=10)),
                ('cor', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('Cao', 'Cachorro'), ('Gato', 'Gato')], max_length=10)),
                ('raca', models.CharField(default='SRD', max_length=20)),
                ('porte', models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MÉDIO', 'Médio'), ('GRANDE', 'Grande')], default='Desconhecido', max_length=10)),
                ('detalhes_medicos', multiselectfield.db.fields.MultiSelectField(choices=[('VACINADO', 'Vacinado'), ('VERMIFUGADO', 'Vermifugado'), ('CASTRADO', 'Castrado')], max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('foto_animal', models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='images/')),
            ],
        ),
    ]
