# Generated by Django 4.2.5 on 2024-10-28 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_adocao', models.CharField(choices=[('analise', 'Análise'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='analise', max_length=100)),
                ('tipo_residencia', models.CharField(choices=[('casa', 'Casa'), ('predio', 'Prédio')], max_length=50)),
                ('telado', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
