# Generated by Django 4.2.5 on 2024-10-24 05:37

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_descricao_animal_detalhes_medicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto_animal',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='media/images'), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Dispobivel', 'disponivel'), ('Adotado', 'adotado')], default='Desconhecido', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tipo',
            field=models.CharField(choices=[('Cao', 'Cachorro'), ('Gato', 'Gato')], max_length=10),
        ),
    ]
