# Generated by Django 4.2.5 on 2024-10-31 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0002_adocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(max_length=50)),
                ('detalhes_medicos', multiselectfield.db.fields.MultiSelectField(choices=[('VACINADO', 'Vacinado'), ('VERMIFUGADO', 'Vermifugado'), ('CASTRADO', 'Castrado')], max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
