# Generated by Django 4.2.5 on 2024-10-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_registromedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='detalhes_medicos',
        ),
    ]
