# Generated by Django 4.2.5 on 2024-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_remove_animal_detalhes_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'disponivel'), ('Adotado', 'adotado')], default='Disponivel', max_length=10),
        ),
    ]
